### PR TITLE
holy shit the curium update

### PR DESCRIPTION
**Pull request by TheNewGuy19**
impale timmy on a metal pike!

### CODE REVIEW

**Comment by JameH2** [comment]
in the words of an austrian femboy, "merged locally"

**Comment by HbmMods** [comment]
mfw (my face when) merge conflicts (it cannot be merged on GH)

**Comment by JameH2** [comment]
i had to cherry pick otherwise 23214328398123 file changes that I didn't bother looking through

**Comment by HbmMods** [comment]
i don't even know how cherrypicking works, git is an enigma to me

**Comment by JameH2** [comment]
you can select commits you like and then merge them instead of the whole pr, which is neat if you have a 70k type situation where the code is unfinished and crashes your game

**Comment by HbmMods** [comment]
and how would i do that?

**Comment by JameH2** [comment]
to avoid context confusion, this conversation was explained on discord

**Comment by 70000hp** [comment]
> you can select commits you like and then merge them instead of the whole pr, which is neat if you have a 70k type situation where the code is unfinished and crashes your game

Kill yourself

**Comment by JameH2** [comment]
i thought i fucking closed this

**Pull request closed without merging**
